[package]
name = "rust_app_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
fusion-hawking = { path = "../../../" }
ctrlc = "3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
